-- =============================================================================
-- Ontario Mental Health Services Analytics — SQL Reference
--
-- Dataset: KHP 2019 Ministry of Health Export (5,945 service records)
-- Schema:  services (one row per service) + service_taxonomy (normalized terms)
-- Author:  Generated by the analytics dashboard backend
-- =============================================================================


-- =============================================================================
-- KPI Queries
-- =============================================================================

-- Total service records
SELECT COUNT(*) AS total_services
FROM services;
-- Result: 5,945

-- Distinct geographic regions (counties)
SELECT COUNT(DISTINCT physical_county) AS total_counties
FROM services;
-- Result: 50 counties across Ontario

-- Bilingual services (EN/FR)
-- Source: "Bilingual - both French and English" or "Bilingue - Français et Anglais"
SELECT COUNT(*) AS bilingual_services
FROM services
WHERE bilingual_service = true;
-- Result: 266

-- LGBTQ+-affirming services
-- Source: Custom_Are services provided to LGBTQ persons? = 'Yes' or 'Oui'
SELECT COUNT(*) AS lgbtq_services
FROM services
WHERE lgbtq_support = true;
-- Result: 248

-- Harm reduction services
-- Source: Custom_Does your program offer a harm reduction approach? = 'Yes' or 'Oui'
SELECT COUNT(*) AS harm_reduction_services
FROM services
WHERE harm_reduction = true;
-- Result: 6


-- =============================================================================
-- Distribution Queries
-- =============================================================================

-- Services by taxonomy category (top 15)
-- Taxonomy terms are normalized into the service_taxonomy table (one row per term)
SELECT
    st.term         AS category,
    COUNT(DISTINCT s.id) AS count
FROM service_taxonomy st
JOIN services s ON s.id = st.service_id
GROUP BY st.term
ORDER BY count DESC
LIMIT 15;

-- Services by county (top 20)
SELECT
    physical_county AS county,
    COUNT(*)        AS count
FROM services
WHERE physical_county IS NOT NULL
GROUP BY physical_county
ORDER BY count DESC
LIMIT 20;

-- Services by city within a county (example: Toronto)
SELECT
    physical_city   AS city,
    COUNT(*)        AS count
FROM services
WHERE physical_county = 'Toronto'
  AND physical_city IS NOT NULL
GROUP BY physical_city
ORDER BY count DESC;


-- =============================================================================
-- Eligibility Queries
-- =============================================================================

-- Age eligibility group distribution
-- Groups are derived from the Custom_Eligibility by Age semicolon-delimited field:
--   Children (0-11)            → ages <5 through 11
--   Adolescents (12-17)        → ages 12 through 17
--   Youth & Young Adults (12-25) → ages spanning 12-25
--   Adults (18+)               → ages 18 and above
--   All Ages                   → full range <5 to >25
SELECT
    eligibility_age_group AS age_group,
    COUNT(*)              AS count
FROM services
WHERE eligibility_age_group IS NOT NULL
GROUP BY eligibility_age_group
ORDER BY count DESC;

-- Gender eligibility distribution
-- Normalized from Custom_Eligibility by Gender:
--   "Females - only" → Female Only
--   "Males - only"   → Male Only
--   Both present     → All Genders
SELECT
    eligibility_by_gender AS gender,
    COUNT(*)              AS count
FROM services
WHERE eligibility_by_gender IS NOT NULL
GROUP BY eligibility_by_gender
ORDER BY count DESC;


-- =============================================================================
-- Language Queries
-- =============================================================================

-- Language availability breakdown
SELECT
    CASE
        WHEN bilingual_service THEN 'Bilingual (EN/FR)'
        WHEN languages_offered_list ILIKE '%français%'
          OR languages_offered_list ILIKE '%french%'
        THEN 'French Only'
        ELSE 'English Only'
    END AS language,
    COUNT(*) AS count
FROM services
GROUP BY 1
ORDER BY count DESC;

-- Services with multi-language support (non-English/French)
SELECT
    languages_offered_list,
    COUNT(*) AS count
FROM services
WHERE languages_offered_list IS NOT NULL
  AND languages_offered_list NOT ILIKE '%english only%'
  AND languages_offered_list NOT ILIKE '%anglais seulement%'
GROUP BY languages_offered_list
ORDER BY count DESC
LIMIT 20;


-- =============================================================================
-- Filtered Service Report Query (used by report table)
-- Supports filters: county, taxonomy term, bilingual, lgbtq, harm_reduction,
--                   age_group, gender, and text search
-- =============================================================================

SELECT
    s.id,
    s.public_name,
    s.official_name,
    STRING_AGG(DISTINCT st.term, ', ')  AS category,
    s.physical_city,
    s.physical_county,
    s.eligibility_by_age,
    s.eligibility_age_group,
    s.eligibility_by_gender,
    s.languages_offered_list,
    s.bilingual_service,
    s.lgbtq_support,
    s.harm_reduction,
    s.normal_wait_time,
    s.website_address
FROM services s
LEFT JOIN service_taxonomy st ON st.service_id = s.id
WHERE
    -- Uncomment and set filters as needed:
    -- s.physical_county = 'Toronto'
    -- AND s.bilingual_service = true
    -- AND s.lgbtq_support = true
    -- AND s.harm_reduction = true
    -- AND s.eligibility_age_group = 'Adolescents (12-17)'
    -- AND s.eligibility_by_gender = 'Female Only'
    -- AND (s.public_name ILIKE '%crisis%' OR s.official_name ILIKE '%crisis%')
    true
GROUP BY s.id
ORDER BY s.public_name
LIMIT 500;


-- =============================================================================
-- Cross-filter analysis examples (used in interviews to explain the model)
-- =============================================================================

-- Bilingual services in Toronto by category
SELECT
    st.term  AS category,
    COUNT(DISTINCT s.id) AS count
FROM services s
JOIN service_taxonomy st ON st.service_id = s.id
WHERE s.physical_county = 'Toronto'
  AND s.bilingual_service = true
GROUP BY st.term
ORDER BY count DESC;

-- LGBTQ+ services serving adolescents
SELECT
    s.physical_county,
    COUNT(*) AS count
FROM services s
WHERE s.lgbtq_support = true
  AND s.eligibility_age_group IN ('Adolescents (12–17)', 'Youth & Young Adults (12–25)')
GROUP BY s.physical_county
ORDER BY count DESC;

-- Services with harm reduction by taxonomy term
SELECT
    st.term AS category,
    COUNT(DISTINCT s.id) AS count
FROM services s
JOIN service_taxonomy st ON st.service_id = s.id
WHERE s.harm_reduction = true
GROUP BY st.term
ORDER BY count DESC;

-- Coverage by county: bilingual + LGBTQ+ + harm reduction combined
SELECT
    s.physical_county,
    COUNT(*) FILTER (WHERE s.bilingual_service)  AS bilingual,
    COUNT(*) FILTER (WHERE s.lgbtq_support)      AS lgbtq,
    COUNT(*) FILTER (WHERE s.harm_reduction)     AS harm_reduction,
    COUNT(*)                                     AS total
FROM services s
GROUP BY s.physical_county
ORDER BY total DESC
LIMIT 20;
